---
- name: Configure Apache Web Server
  hosts: all
  become: true

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install Apache web server
      package:
        name: apache2
        state: present
      become: true

    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Ensure Apache is running
      wait_for:
        port: 80
      delay: 10

    - name: Create index.html file
      template:
        src: index.html.j2
        dest: /var/www/html/index.html

